my_data[[1]][5,109] <- "cargo_2"
my_data[[1]][5,5] <- "APPATERNO"
my_data[[1]][5,6] <- "APMATERNO"
my_data[[1]][5,69] <- "MCHC_2"
names(my_data[[1]]) <- my_data[[1]][5,]
by = join_by(dni)
## my_data[[1]]

my_data[[1]] <- my_data[[1]] |>
  mutate(`FECHA DE ATENCION` = format(as.Date(as.numeric(`FECHA DE ATENCION`),origin = "1899-12-30"), "%Y")) |>
  filter(!is.na(`N°`)) |>
  filter(!`N°` == "N°") |>
  rowid_to_column("ID") |>
  mutate(source = files[1]) 
  
my_data[[1]] <-  my_data[[1]] %>%
  select(anho = matches("FECHA DE ATENCION"),
         id = matches("^ID$"),
         source = matches("source"),
         dni = matches("DNI"),
         edad = matches("EDAD"),
         sexo = matches("SEXO"),
         perabd = matches("PERIMETRO"),
         presionarterial = matches("DX PA"),
         hb = matches("HEMOGRAMA - HEMOGLOBINA"),
         plaq = matches("PLAQUETAS"),
         leuc = matches("GLOBULOS? BLANCOS?"),
         glu = matches("^GLUCOSA"),
         ct = matches("COLESTEROL TOTAL"),
         trig = matches("TRIGLI"),
         hdl = matches("HDL"),
         ldl = matches("LDL"),
         presion_sis = matches("SIST"),
         presion_dia = matches("DIAST"),
         imc = matches("IMC"),
         # fc = matches("FC"),
         oftalmo = matches("OFTALMO"),
         audio = matches("AUDIO"),
         rx_torax = matches("RX"),
         ekg = matches("EKG"))

## my_data[[2]]

my_data[[2]] <- my_data[[2]] |>
  # filter(!is.na(`N°`)) |>
  # filter(!`N°` == "N°") |>
  rowid_to_column("ID") |>
  mutate(source = files[2])

my_data[[2]] <- my_data[[2]] |>
  select(anho = matches("FECHA DE ATENCION"),
         id = matches("^ID$"),
         source = matches("source"),
         dni = matches("DNI"),
         edad = matches("EDAD"),
         sexo = matches("SEXO"),
         perabd = matches("PERIMETRO"),
         presionarterial = matches("DX PA"),
         hb = matches("HEMOGRAMA - HEMOGLOBINA"),
         plaq = matches("PLAQUETAS"),
         leuc = matches("GLOBULOS? BLANCOS?"),
         glu = matches("^GLUCOSA"),
         ct = matches("VALOR DE COLESTEROL TOTAL"),
         trig = matches("VALOR DE TRIGLI"),
         hdl = matches("VALOR HDL"),
         ldl = matches("VALOR DE LDL"),
         presion_sis = matches("SIST"),
         presion_dia = matches("DIAST"),
         imc = matches("^IMC.*23$"),
         # matches("FC"),
         oftalmo = matches("OFTALMO"),
         audio = matches("AUDIO"),
         rx_torax = matches("RX"),
         ekg = matches("EKG"))

## my_data[[3]]

my_data[[3]] <- my_data[[3]] |>
  # filter(!is.na(`N°`)) |>
  # filter(!`N°` == "N°") |>
  rowid_to_column("ID") |>
  mutate(source = files[3])

my_data[[3]] <- my_data[[3]] |>
  select(anho = matches("FECHA DE ATENCION"),
         id = matches("^ID$"),
         source = matches("source"),
         dni = matches("DNI"),
         edad = matches("EDAD"),
         sexo = matches("SEXO"),
         perabd = matches("PERIMETRO"),
         presionarterial = matches("DX PA"),
         hb = matches("HEMOGRAMA - HEMOGLOBINA"),
         plaq = matches("PLAQUETAS"),
         leuc = matches("GLOBULOS? BLANCOS?"),
         glu = matches("^GLUCOSA"),
         ct = matches("VALOR DE COLESTEROL TOTAL"),
         trig = matches("VALOR DE TRIGLI"),
         hdl = matches("VALOR HDL"),
         ldl = matches("VALOR DE LDL"),
         presion_sis = matches("SIST"),
         presion_dia = matches("DIAST"),
         imc = matches("^IMC.*23$"),
         # matches("FC"),
         oftalmo = matches("OFTALMO"),
         audio = matches("AUDIO"),
         rx_torax = matches("RX"),
         ekg = matches("EKG"))


## my_data[[4]]

my_data[[4]] <- my_data[[4]] |>
  mutate(`Fecha de EMO` = format(as.Date(as.numeric(`Fecha de EMO`),origin = "1899-12-30"), "%Y")) |>
  # filter(!is.na(`N°`)) |>
  # filter(!`N°` == "N°") |>
  rowid_to_column("ID") |>
  mutate(source = files[4])

my_data[[4]] <- my_data[[4]] |>
  select(anho = matches("FECHA DE EMO"),
         id = matches("^ID$"),
         source = matches("source"),
         dni = matches("DNI"),
         edad = matches("^EDAD"),
         sexo = matches("SEXO"),
         perabd = matches("PERIMETRO"),
         presionarterial = matches("^PA$"),
         hb = matches("^HB$"),
         plaq = matches("^PLAQ"),
         leuc = matches("^LEUC"),
         glu = matches("^GLUCOSA"),
         ct = matches("COLESTEROL TOTAL"),
         trig = matches("^TRIGLI"),
         hdl = matches("VALOR HDL"),
         ldl = matches("VALOR DE LDL"),
         presion_sis = matches("SIST"),
         presion_dia = matches("DIAST"),
         imc = matches("^IMC"),
         # matches("FC"),
         oftalmo = matches("OFTALMO"),
         audio = matches("AUDIO"),
         rx_torax = matches("RX"),
         ekg = matches("EKG"))

### 11

colnames11 <- c(
  "Nombres y Apellidos",
  "DNI",
  "Genero",
  "Edad",
  "FechaNacimiento",
  "FechaRegistro",
  "Fecha Evaluación",
  "Empresa",
  "Resultado",
  "Anti Hvc",
  "Antigeno Especifico Prostatico (Psa)",
  "Bk Directo Coloración Zhiel Neelsen",
  "Bk Directo Especimen",
  "Colesterol Total",
  "orina Glucosa",
  "orina Hematies",
  "orina Hemoglobina",
  "orina Leucocitos",
  "Glucosa",
  "Factor Rh",
  "Grupo Sanguineo",
  "Hdl Colesterol",
  "Eosinofilos",
  "Hematocrito",
  "Hemoglobina",
  "Plaquetas",
  "Hiv Ag/Ac",
  "Ldl Colesterol",
  "Serologia  Sifilis (Rpr)",
  "Trigliceridos"
)

names(my_data[[11]]) <- colnames11

my_data[[11]] <- my_data[[11]] |>
  mutate(`Fecha Evaluación` = format(as.Date(`Fecha Evaluación`, "%d/%m/%Y"), "%Y")) |>
  # filter(!is.na(`Glucosa`)) |>
  # filter(!`N°` == "N°") |>
  rowid_to_column("ID") |>
  mutate(source = files[11]) |>
  filter(ID > 2)

my_data[[11]] <- my_data[[11]] |>
  select(anho = matches("FECHA EVALUACIÓN"),
         id = matches("^ID$"),
         source = matches("source"),
         dni = matches("DNI"),
         edad = matches("^EDAD"),
         sexo = matches("SEXO"),
         perabd = matches("PERIMETRO"),
         presionarterial = matches("^PA$"),
         hb = matches("^Hemo"),
         plaq = matches("^PLAQ"),
         leuc = matches("^LEUC"),
         glu = matches("^GLUCOSA"),
         ct = matches("COLESTEROl TOTAL"),
         trig = matches("TRIGLI"),
         hdl = matches("^HDL"),
         ldl = matches("^LDL"),
         presion_sis = matches("PAS"),
         presion_dia = matches("PAD"),
         imc = matches("^IMC"),
         fc = matches("FC"),
         oftalmo = matches("OFTALMO"),
         audio = matches("AUDIO"),
         rx_torax = matches("torax$"),
         ekg = matches("EKG")) |>
  mutate(dni = zoo::na.locf(dni)) |>
  replace_na(as.list(rep.na)) |>
  mutate(edad = as.numeric(str_extract(edad, "[0-9]+"))) |>
  mutate(across(hb:ldl, as.numeric)) |>
  aggregate(cbind(edad,hb,plaq,glu,ct,trig,hdl,ldl) ~ dni, sum)



## my_data[[5]]

colnames5 <- c("1 NUMERO DE HISTORIA",
               "2 APELLIDOS Y NOMBRES",
               "3 PUESTO DE TRABAJO",
               "4 FECHA DE NACIMIENTO",
               "5 EDAD",
               "6 DNI",
               "7 DIRECCION",
               "8 TELEFONO",
               "9 PERFIL",
               "10 PROYECTO",
               "11 AREA",
               "12 Empresa",
               "13 TIPO DE EXAMEN",
               "14 FECHA DE ATENCIÓN",
               "15 FECHA DE CADUCIDAD",
               "16 SEXO",
               "17 ESTADO CIVIL",
               "18 ANTECEDENTES PERSONALES",
               "19 ANTECEDENTES FAMILIARES",
               "20 RAM (REACCION ALERGICA A MEDICAMENTOS)",
               "21 FREC. ALCOHOL",
               "22 TABACO",
               "23 DROGAS",
               "24 MEDICAMENTOS",
               "25 ANTECEDENTES OCUPACIONALES",
               "26 ACCIDENTES DE TRABAJO",
               "27 ANAMNESIS",
               "28 PRESION SISTOLICA",
               "29 PRESION DIASTOLICA",
               "30 QRS",
               "31 PR",
               "32 QT",
               "33 EJE",
               "34 ANTECEDENTES CARDIOVASCULARES:",
               "35 DIAGNOSTICO 1",
               "36 CIE 10",
               "37 RECOMENDACIÓN",
               "38 DIAGNOSTICO 2",
               "39 CIE 10",
               "40 RECOMENDACIÓN",
               "41 F. CARDIACA",
               "42 F. RESPIRATORIA",
               "43 SAT. O2",
               "44 PESO",
               "45 TALLA",
               "46 IMC",
               "47 PER. AMBOMINAL",
               "48 TEMPERATURA",
               "49 CINTURA",
               "50 CADERA",
               "51 INDICE CINTURA/CADERA",
               "52 DIAGNOSTICO 1",
               "53 CIE 10",
               "54 RECOMENDACIÓN",
               "55 DIAGNOSTICO 1",
               "56 CIE 10",
               "57 RECOMENDACIÓN",
               "58 DIAGNOSTICO 2",
               "59 CIE 10",
               "60 RECOMENDACIÓN",
               "61 AGUDEZA VISUAL LEJOS SIN CORRECTORES - OI",
               "62 AGUDEZA VISUAL LEJOS SIN CORRECTORES - OD",
               "63 AGUDEZA VISUAL LEJOS CON CORRECTORES - OI",
               "64 AGUDEZA VISUAL LEJOS CON CORRECTORES - OD",
               "65 AGUDEZA VISUAL CERCA SIN CORRECTORES - OI",
               "66 AGUDEZA VISUAL CERCA SIN CORRECTORES - OD",
               "67 AGUDEZA VISUAL CERCA CON CORRECTORES - OI",
               "68 AGUDEZA VISUAL CERCA CON CORRECTORES - OD",
               "69 AGUJERO ESTENOPEICO OD",
               "70 AGUJERO ESTENOPEICO OI",
               "71 TEST DE ISHIHARA",
               "72 ESTEREOPSIS",
               "73 PSICOSENSOMETRICO",
               "74 DIAGNOSTICO 1",
               "75 CIE 10",
               "76 RECOMENDACIÓN",
               "77 DIAGNOSTICO 2",
               "78 CIE 10",
               "79 RECOMENDACIÓN",
               "80 DIAGNOSTICO 3",
               "81 CIE 10",
               "82 RECOMENDACIÓN",
               "83 DIAGNOSTICO 4",
               "84 CIE 10",
               "85 RECOMENDACIÓN",
               "86 DIAGNOSTICO 5",
               "87 CIE 10",
               "88 RECOMENDACIÓN",
               "89 250",
               "90 500",
               "91 1000",
               "92 2000",
               "93 3000",
               "94 4000",
               "95 6000",
               "96 8000",
               "97 250",
               "98 500",
               "99 1000",
               "100 2000",
               "101 3000",
               "102 4000",
               "103 6000",
               "104 8000",
               "105 250",
               "106 500",
               "107 1000",
               "108 2000",
               "109 3000",
               "110 4000",
               "111 6000",
               "112 8000",
               "113 250",
               "114 500",
               "115 1000",
               "116 2000",
               "117 3000",
               "118 4000",
               "119 6000",
               "120 8000",
               "121 OIDO DERECHO",
               "122 OIDO IZQUIERDO",
               "123 TIEMPO DIARIO DE EXPOSICION (HORAS)",
               "124 AÑOS DE EXPOSICION",
               "125 USO DE EQUIPOS DE PROTECCION AUDITIVOS",
               "126 DIAGNOSTICO ",
               "127 CIE 10",
               "128 RECOMENDACIÓN",
               "129 DIAGNOSTICO ",
               "130 CIE 10",
               "131 RECOMENDACIÓN",
               "132 FVC",
               "133 %",
               "134 FEV1",
               "135 %",
               "136 FEV1/FVC",
               "137 %",
               "138 FEF25-75%",
               "139 %",
               "140 CALIDAD",
               "141 DIAGNOSTICO 1",
               "142 CIE 10",
               "143 RECOMENCACIÓN 1",
               "144 DIAGNOSTICO",
               "145 CIE 10",
               "146 RECOMENCACIÓN",
               "147 DIAGNOSTICO 2",
               "148 CIE 10",
               "149 RECOMENCACIÓN",
               "150 DIAGNOSTICO 3",
               "151 CIE 10",
               "152 RECOMENCACIÓN",
               "153 DIAGNOSTICO_1",
               "154 CIE10",
               "155 RECOMENDACIÓN",
               "156 DIAGNOSTICO_2",
               "157 CIE10",
               "158 RECOMENDACIÓN",
               "159 DIAGNOSTICO_3",
               "160 CIE10",
               "161 RECOMENDACIÓN",
               "162 DIAGNOSTICO_4",
               "163 CIE10",
               "164 RECOMENDACIÓN",
               "165 DIAGNOSTICO_5",
               "166 CIE10",
               "167 RECOMENDACIÓN",
               "168 DIAGNOSTICO_6",
               "169 CIE10",
               "170 RECOMENDACIÓN",
               "171 DIAGNOSTICO_7",
               "172 CIE10",
               "173 RECOMENDACIÓN",
               "174 DIAGNOSTICO_8",
               "175 CIE10",
               "176 RECOMENDACIÓN",
               "177 APTITUD",
               "178 MOTIVO",
               "179 RESTRICCIONES")

names(my_data[[5]]) <- colnames5

my_data[[5]] <- my_data[[5]] |>
  mutate(`14 FECHA DE ATENCIÓN` = format(as.Date(`14 FECHA DE ATENCIÓN`, "%d-%m-%Y"), "%Y")) |>
  filter(!is.na(`1 NUMERO DE HISTORIA`)) |>
  # filter(!`N°` == "N°") |>
  rowid_to_column("ID") |>
  mutate(source = files[5])

my_data[[5]] <- my_data[[5]] |>
  select(anho = matches("FECHA DE ATENCIÓN"),
         id = matches("^ID$"),
         source = matches("source"),
         dni = matches("DNI"),
         edad = matches("EDAD"),
         sexo = matches("SEXO"),
         perabd = matches("47 PER"),
         presionarterial = matches("^PA$"),
         hb = matches("^HB$"),
         plaq = matches("^PLAQ"),
         leuc = matches("^LEUC"),
         glu = matches("^GLUCOSA"),
         ct = matches("COLESTEROL TOTAL"),
         trig = matches("TRIGLI"),
         hdl = matches("VALOR HDL"),
         ldl = matches("VALOR DE LDL"),
         presion_sis = matches("SIST"),
         presion_dia = matches("DIAST"),
         imc = matches("^[0-9]+ IMC"),
         fc = matches("^41 "),
         oftalmo = matches("^74 DIAG"),
         audio = matches("126 DIAG"),
         rx_torax = matches("144 DIAGN"),
         ekg = matches("35 DIAGNOSTICO")) |>
  left_join(my_data[[11]] |> select(-edad), by)
  #EKG

## my_data[[6]]

colnames6 <- c("1 NUMERO DE HISTORIA",
               "2 APELLIDOS Y NOMBRES",
               "3 PUESTO DE TRABAJO",
               "4 FECHA DE NACIMIENTO",
               "5 EDAD",
               "6 DNI",
               "7 DIRECCION",
               "8 TELEFONO",
               "9 PERFIL",
               "10 PROYECTO",
               "11 AREA",
               "12 Empresa",
               "13 TIPO DE EXAMEN",
               "14 FECHA DE ATENCIÓN",
               "15 FECHA DE CADUCIDAD",
               "16 SEXO",
               "17 ESTADO CIVIL",
               "18 ANTECEDENTES PERSONALES",
               "19 ANTECEDENTES FAMILIARES",
               "20 RAM (REACCION ALERGICA A MEDICAMENTOS)",
               "21 FREC. ALCOHOL",
               "22 TABACO",
               "23 DROGAS",
               "24 MEDICAMENTOS",
               "25 ANTECEDENTES OCUPACIONALES",
               "26 ACCIDENTES DE TRABAJO",
               "27 ANAMNESIS",
               "28 PRESION SISTOLICA",
               "29 PRESION DIASTOLICA",
               "30 QRS",
               "31 PR",
               "32 QT",
               "33 EJE",
               "34 ANTECEDENTES CARDIOVASCULARES:",
               "35 DIAGNOSTICO 1",
               "36 CIE 10",
               "37 RECOMENDACIÓN",
               "38 F. CARDIACA",
               "39 F. RESPIRATORIA",
               "40 SAT. O2",
               "41 PESO",
               "42 TALLA",
               "43 IMC",
               "44 PER. AMBOMINAL",
               "45 TEMPERATURA",
               "46 CINTURA",
               "47 CADERA",
               "48 INDICE CINTURA/CADERA",
               "49 DIAGNOSTICO 1",
               "50 CIE 10",
               "51 RECOMENDACIÓN",
               "52 DIAGNOSTICO 1",
               "53 CIE 10",
               "54 RECOMENDACIÓN",
               "55 DIAGNOSTICO 2",
               "56 CIE 10",
               "57 RECOMENDACIÓN",
               "58 DIAGNOSTICO 3",
               "59 CIE 10",
               "60 RECOMENDACIÓN",
               "61 DIAGNOSTICO 4",
               "62 CIE 10",
               "63 RECOMENDACIÓN",
               "64 AGUDEZA VISUAL LEJOS SIN CORRECTORES - OI",
               "65 AGUDEZA VISUAL LEJOS SIN CORRECTORES - OD",
               "66 AGUDEZA VISUAL LEJOS CON CORRECTORES - OI",
               "67 AGUDEZA VISUAL LEJOS CON CORRECTORES - OD",
               "68 AGUDEZA VISUAL CERCA SIN CORRECTORES - OI",
               "69 AGUDEZA VISUAL CERCA SIN CORRECTORES - OD",
               "70 AGUDEZA VISUAL CERCA CON CORRECTORES - OI",
               "71 AGUDEZA VISUAL CERCA CON CORRECTORES - OD",
               "72 AGUJERO ESTENOPEICO OD",
               "73 AGUJERO ESTENOPEICO OI",
               "74 TEST DE ISHIHARA",
               "75 ESTEREOPSIS",
               "76 PSICOSENSOMETRICO",
               "77 DIAGNOSTICO 1",
               "78 CIE 10",
               "79 RECOMENDACIÓN",
               "80 DIAGNOSTICO 2",
               "81 CIE 10",
               "82 RECOMENDACIÓN",
               "83 DIAGNOSTICO 3",
               "84 CIE 10",
               "85 RECOMENDACIÓN",
               "86 250",
               "87 500",
               "88 1000",
               "89 2000",
               "90 3000",
               "91 4000",
               "92 6000",
               "93 8000",
               "94 250",
               "95 500",
               "96 1000",
               "97 2000",
               "98 3000",
               "99 4000",
               "100 6000",
               "101 8000",
               "102 250",
               "103 500",
               "104 1000",
               "105 2000",
               "106 3000",
               "107 4000",
               "108 6000",
               "109 8000",
               "110 250",
               "111 500",
               "112 1000",
               "113 2000",
               "114 3000",
               "115 4000",
               "116 6000",
               "117 8000",
               "118 OIDO DERECHO",
               "119 OIDO IZQUIERDO",
               "120 TIEMPO DIARIO DE EXPOSICION (HORAS)",
               "121 AÑOS DE EXPOSICION",
               "122 USO DE EQUIPOS DE PROTECCION AUDITIVOS",
               "123 DIAGNOSTICO ",
               "124 CIE 10",
               "125 RECOMENDACIÓN",
               "126 DIAGNOSTICO ",
               "127 CIE 10",
               "128 RECOMENDACIÓN",
               "129 FVC",
               "130 %",
               "131 FEV1",
               "132 %",
               "133 FEV1/FVC",
               "134 %",
               "135 FEF25-75%",
               "136 %",
               "137 CALIDAD",
               "138 DIAGNOSTICO 1",
               "139 CIE 10",
               "140 RECOMENCACIÓN 1",
               "141 DIAGNOSTICO 2",
               "142 CIE 10",
               "143 RECOMENCACIÓN 2",
               "144 DIAGNOSTICO 3",
               "145 CIE 10",
               "146 RECOMENCACIÓN 3",
               "147 DIAGNOSTICO",
               "148 CIE 10",
               "149 DIAGNOSTICO_1",
               "150 CIE10",
               "151 RECOMENDACIÓN",
               "152 DIAGNOSTICO_2",
               "153 CIE10",
               "154 RECOMENDACIÓN",
               "155 DIAGNOSTICO_3",
               "156 CIE10",
               "157 RECOMENDACIÓN",
               "158 DIAGNOSTICO_4",
               "159 CIE10",
               "160 RECOMENDACIÓN",
               "161 APTITUD",
               "162 MOTIVO",
               "163 RESTRICCIONES"
)

names(my_data[[6]]) <- colnames6

my_data[[6]] <- my_data[[6]] |>
  mutate(`14 FECHA DE ATENCIÓN` = format(as.Date(`14 FECHA DE ATENCIÓN`, "%d-%m-%Y"), "%Y")) |>
  filter(!is.na(`1 NUMERO DE HISTORIA`)) |>
  # filter(!`N°` == "N°") |>
  rowid_to_column("ID") |>
  mutate(source = files[6])

my_data[[6]] <- my_data[[6]] |>
  select(anho = matches("FECHA DE ATENCIÓN"),
         id = matches("^ID$"),
         source = matches("source"),
         dni = matches("DNI"),
         edad = matches("EDAD"),
         sexo = matches("SEXO"),
         perabd = matches("44 PER"),
         presionarterial = matches("^PA$"),
         hb = matches("^HB$"),
         plaq = matches("^PLAQ"),
         leuc = matches("^LEUC"),
         glu = matches("^GLUCOSA"),
         ct = matches("COLESTEROL TOTAL"),
         trig = matches("TRIGLI"),
         hdl = matches("VALOR HDL"),
         ldl = matches("VALOR DE LDL"),
         presion_sis = matches("SIST"),
         presion_dia = matches("DIAST"),
         imc = matches("^[0-9]+ IMC"),
         fc = matches("F\\. CARD"),
         oftalmo = matches("^77 DIAG"),
         audio = matches("123 DIAG"),
         rx_torax = matches("138 DIAGN"),
         ekg = matches("35 DIAGNOSTICO")) |>
  left_join(my_data[[11]] |> select(-edad), by)


### 7

colnames7 <- c(
  "1 NUMERO DE HISTORIA",
  "2 APELLIDOS Y NOMBRES",
  "3 PUESTO DE TRABAJO",
  "4 FECHA DE NACIMIENTO",
  "5 EDAD",
  "6 DNI",
  "7 DIRECCION",
  "8 TELEFONO",
  "9 PERFIL",
  "10 PROYECTO",
  "11 AREA",
  "12 Empresa",
  "13 TIPO DE EXAMEN",
  "14 FECHA DE ATENCIÓN",
  "15 FECHA DE CADUCIDAD",
  "16 SEXO",
  "17 ESTADO CIVIL",
  "18 ANTECEDENTES PERSONALES",
  "19 ANTECEDENTES FAMILIARES",
  "20 RAM (REACCION ALERGICA A MEDICAMENTOS)",
  "21 FREC. ALCOHOL",
  "22 TABACO",
  "23 DROGAS",
  "24 MEDICAMENTOS",
  "25 ANTECEDENTES OCUPACIONALES",
  "26 ACCIDENTES DE TRABAJO",
  "27 ANAMNESIS",
  "28 PRESION SISTOLICA",
  "29 PRESION DIASTOLICA",
  "30 QRS",
  "31 PR",
  "32 QT",
  "33 EJE",
  "34 ANTECEDENTES CARDIOVASCULARES:",
  "35 DIAGNOSTICO 1",
  "36 CIE 10",
  "37 RECOMENDACIÓN",
  "38 F. CARDIACA",
  "39 F. RESPIRATORIA",
  "40 SAT. O2",
  "41 PESO",
  "42 TALLA",
  "43 IMC",
  "44 PER. AMBOMINAL",
  "45 TEMPERATURA",
  "46 CINTURA",
  "47 CADERA",
  "48 INDICE CINTURA/CADERA",
  "49 DIAGNOSTICO 1",
  "50 CIE 10",
  "51 RECOMENDACIÓN",
  "52 DIAGNOSTICO 1",
  "53 CIE 10",
  "54 RECOMENDACIÓN",
  "55 DIAGNOSTICO 2",
  "56 CIE 10",
  "57 AGUDEZA VISUAL LEJOS SIN CORRECTORES - OI",
  "58 AGUDEZA VISUAL LEJOS SIN CORRECTORES - OD",
  "59 AGUDEZA VISUAL LEJOS CON CORRECTORES - OI",
  "60 AGUDEZA VISUAL LEJOS CON CORRECTORES - OD",
  "61 AGUDEZA VISUAL CERCA SIN CORRECTORES - OI",
  "62 AGUDEZA VISUAL CERCA SIN CORRECTORES - OD",
  "63 AGUDEZA VISUAL CERCA CON CORRECTORES - OI",
  "64 AGUDEZA VISUAL CERCA CON CORRECTORES - OD",
  "65 AGUJERO ESTENOPEICO OD",
  "66 AGUJERO ESTENOPEICO OI",
  "67 TEST DE ISHIHARA",
  "68 ESTEREOPSIS",
  "69 DIAGNOSTICO 1",
  "70 CIE 10",
  "71 RECOMENDACIÓN",
  "72 DIAGNOSTICO 2",
  "73 CIE 10",
  "74 RECOMENDACIÓN",
  "75 DIAGNOSTICO 3",
  "76 CIE 10",
  "77 RECOMENDACIÓN",
  "78 DIAGNOSTICO 4",
  "79 CIE 10",
  "80 250",
  "81 500",
  "82 1000",
  "83 2000",
  "84 3000",
  "85 4000",
  "86 6000",
  "87 8000",
  "88 250",
  "89 500",
  "90 1000",
  "91 2000",
  "92 3000",
  "93 4000",
  "94 6000",
  "95 8000",
  "96 250",
  "97 500",
  "98 1000",
  "99 2000",
  "100 3000",
  "101 4000",
  "102 6000",
  "103 8000",
  "104 250",
  "105 500",
  "106 1000",
  "107 2000",
  "108 3000",
  "109 4000",
  "110 6000",
  "111 8000",
  "112 OIDO DERECHO",
  "113 OIDO IZQUIERDO",
  "114 TIEMPO DIARIO DE EXPOSICION (HORAS)",
  "115 AÑOS DE EXPOSICION",
  "116 USO DE EQUIPOS DE PROTECCION AUDITIVOS",
  "117 DIAGNOSTICO ",
  "118 CIE 10",
  "119 RECOMENDACIÓN",
  "120 DIAGNOSTICO ",
  "121 CIE 10",
  "122 RECOMENDACIÓN",
  "123 FVC",
  "124 %",
  "125 FEV1",
  "126 %",
  "127 FEV1/FVC",
  "128 %",
  "129 FEF25-75%",
  "130 %",
  "131 CALIDAD",
  "132 DIAGNOSTICO 1",
  "133 CIE 10",
  "134 RECOMENCACIÓN 1",
  "135 DIAGNOSTICO",
  "136 CIE 10",
  "137 RECOMENCACIÓN",
  "138 DIAGNOSTICO 2",
  "139 DIAGNOSTICO_1",
  "140 CIE10",
  "141 RECOMENDACIÓN",
  "142 DIAGNOSTICO_2",
  "143 CIE10",
  "144 RECOMENDACIÓN",
  "145 DIAGNOSTICO_3",
  "146 CIE10",
  "147 RECOMENDACIÓN",
  "148 DIAGNOSTICO_4",
  "149 CIE10",
  "150 RECOMENDACIÓN",
  "151 DIAGNOSTICO_5",
  "152 CIE10",
  "153 RECOMENDACIÓN",
  "154 DIAGNOSTICO_6",
  "155 CIE10",
  "156 RECOMENDACIÓN",
  "157 DIAGNOSTICO_7",
  "158 CIE10",
  "159 RECOMENDACIÓN",
  "160 DIAGNOSTICO_8",
  "161 CIE10",
  "162 RECOMENDACIÓN",
  "163 DIAGNOSTICO_9",
  "164 CIE10",
  "165 RECOMENDACIÓN",
  "166 DIAGNOSTICO_10",
  "167 CIE10",
  "168 RECOMENDACIÓN",
  "169 DIAGNOSTICO_11",
  "170 CIE10",
  "171 RECOMENDACIÓN",
  "172 DIAGNOSTICO_12",
  "173 CIE10",
  "174 RECOMENDACIÓN",
  "175 APTITUD",
  "176 MOTIVO",
  "177 RESTRICCIONES"
)

names(my_data[[7]]) <- colnames7

my_data[[7]] <- my_data[[7]] |>
  mutate(`14 FECHA DE ATENCIÓN` = format(as.Date(`14 FECHA DE ATENCIÓN`, "%d-%m-%Y"), "%Y")) |>
  filter(!is.na(`1 NUMERO DE HISTORIA`)) |>
  # filter(!`N°` == "N°") |>
  rowid_to_column("ID") |>
  mutate(source = files[7])

my_data[[7]] <- my_data[[7]] |>
  select(anho = matches("FECHA DE ATENCIÓN"),
         id = matches("^ID$"),
         source = matches("source"),
         dni = matches("DNI"),
         edad = matches("EDAD"),
         sexo = matches("SEXO"),
         perabd = matches("44 PER"),
         presionarterial = matches("^PA$"),
         hb = matches("^HB$"),
         plaq = matches("^PLAQ"),
         leuc = matches("^LEUC"),
         glu = matches("^GLUCOSA"),
         ct = matches("COLESTEROL TOTAL"),
         trig = matches("TRIGLI"),
         hdl = matches("VALOR HDL"),
         ldl = matches("VALOR DE LDL"),
         presion_sis = matches("SIST"),
         presion_dia = matches("DIAST"),
         imc = matches("^[0-9]+ IMC"),
         fc = matches("F\\. CARD"),
         oftalmo = matches("^69 DIAG"),
         audio = matches("117 DIAG"),
         rx_torax = matches("135 DIAGN"),
         ekg = matches("^35 DIAGNOSTICO")) |>
  left_join(my_data[[11]] |> select(-edad), by)

### 8

colnames8 <- c(
  "1 NUMERO DE HISTORIA",
  "2 APELLIDOS Y NOMBRES",
  "3 PUESTO DE TRABAJO",
  "4 FECHA DE NACIMIENTO",
  "5 EDAD",
  "6 DNI",
  "7 DIRECCION",
  "8 TELEFONO",
  "9 PERFIL",
  "10 PROYECTO",
  "11 AREA",
  "12 Empresa",
  "13 TIPO DE EXAMEN",
  "14 FECHA DE ATENCIÓN",
  "15 FECHA DE CADUCIDAD",
  "16 SEXO",
  "17 ESTADO CIVIL",
  "18 ANTECEDENTES PERSONALES",
  "19 ANTECEDENTES FAMILIARES",
  "20 RAM (REACCION ALERGICA A MEDICAMENTOS)",
  "21 FREC. ALCOHOL",
  "22 TABACO",
  "23 DROGAS",
  "24 MEDICAMENTOS",
  "25 ANTECEDENTES OCUPACIONALES",
  "26 ACCIDENTES DE TRABAJO",
  "27 ANAMNESIS",
  "28 PRESION SISTOLICA",
  "29 PRESION DIASTOLICA",
  "30 QRS",
  "31 PR",
  "32 QT",
  "33 EJE",
  "34 ANTECEDENTES CARDIOVASCULARES:",
  "35 DIAGNOSTICO 1",
  "36 CIE 10",
  "37 RECOMENDACIÓN",
  "38 DIAGNOSTICO 2",
  "39 F. CARDIACA",
  "40 F. RESPIRATORIA",
  "41 SAT. O2",
  "42 PESO",
  "43 TALLA",
  "44 IMC",
  "45 PER. AMBOMINAL",
  "46 CINTURA ",
  "47 CADERA",
  "48 INDICE CINTURA/CADERA",
  "49 DIAGNOSTICO 1",
  "50 CIE 10",
  "51 RECOMENDACIÓN",
  "52 DIAGNOSTICO 1",
  "53 CIE 10",
  "54 AGUDEZA VISUAL LEJOS SIN CORRECTORES - OI",
  "55 AGUDEZA VISUAL LEJOS SIN CORRECTORES - OD",
  "56 AGUDEZA VISUAL LEJOS CON CORRECTORES - OI",
  "57 AGUDEZA VISUAL LEJOS CON CORRECTORES - OD",
  "58 AGUDEZA VISUAL CERCA SIN CORRECTORES - OI",
  "59 AGUDEZA VISUAL CERCA SIN CORRECTORES - OD",
  "60 AGUDEZA VISUAL CERCA CON CORRECTORES - OI",
  "61 AGUDEZA VISUAL CERCA CON CORRECTORES - OD",
  "62 AGUJERO ESTENOPEICO OD",
  "63 AGUJERO ESTENOPEICO OI",
  "64 TEST DE ISHIHARA",
  "65 ESTEREOPSIS",
  "66 DIAGNOSTICO 1",
  "67 CIE 10",
  "68 RECOMENDACIÓN",
  "69 DIAGNOSTICO 2",
  "70 CIE 10",
  "71 RECOMENDACIÓN",
  "72 DIAGNOSTICO 3",
  "73 CIE 10",
  "74 RECOMENDACIÓN",
  "75 DIAGNOSTICO 4",
  "76 CIE 10",
  "77 RECOMENDACIÓN",
  "78 DIAGNOSTICO 5",
  "79 CIE 10",
  "80 250",
  "81 500",
  "82 1000",
  "83 2000",
  "84 3000",
  "85 4000",
  "86 6000",
  "87 8000",
  "88 250",
  "89 500",
  "90 1000",
  "91 2000",
  "92 3000",
  "93 4000",
  "94 6000",
  "95 8000",
  "96 250",
  "97 500",
  "98 1000",
  "99 2000",
  "100 3000",
  "101 4000",
  "102 6000",
  "103 8000",
  "104 250",
  "105 500",
  "106 1000",
  "107 2000",
  "108 3000",
  "109 4000",
  "110 6000",
  "111 8000",
  "112 OIDO DERECHO",
  "113 OIDO IZQUIERDO",
  "114 TIEMPO DIARIO DE EXPOSICION (HORAS)",
  "115 AÑOS DE EXPOSICION",
  "116 USO DE EQUIPOS DE PROTECCION AUDITIVOS",
  "117 DIAGNOSTICO ",
  "118 CIE 10",
  "119 RECOMENDACIÓN",
  "120 DIAGNOSTICO ",
  "121 CIE 10",
  "122 RECOMENDACIÓN",
  "123 FVC",
  "124 %",
  "125 FEV1",
  "126 %",
  "127 FEV1/FVC",
  "128 %",
  "129 FEF25-75%",
  "130 %",
  "131 CALIDAD",
  "132 DIAGNOSTICO 1",
  "133 CIE 10",
  "134 RECOMENCACIÓN 1",
  "135 DIAGNOSTICO",
  "136 DIAGNOSTICO_1",
  "137 CIE10",
  "138 RECOMENDACIÓN",
  "139 DIAGNOSTICO_2",
  "140 CIE10",
  "141 RECOMENDACIÓN",
  "142 DIAGNOSTICO_3",
  "143 CIE10",
  "144 RECOMENDACIÓN",
  "145 DIAGNOSTICO_4",
  "146 CIE10",
  "147 RECOMENDACIÓN",
  "148 DIAGNOSTICO_5",
  "149 CIE10",
  "150 RECOMENDACIÓN",
  "151 DIAGNOSTICO_6",
  "152 CIE10",
  "153 RECOMENDACIÓN",
  "154 DIAGNOSTICO_7",
  "155 CIE10",
  "156 RECOMENDACIÓN",
  "157 DIAGNOSTICO_8",
  "158 CIE10",
  "159 RECOMENDACIÓN",
  "160 DIAGNOSTICO_9",
  "161 CIE10",
  "162 RECOMENDACIÓN",
  "163 DIAGNOSTICO_10",
  "164 CIE10",
  "165 RECOMENDACIÓN",
  "166 DIAGNOSTICO_11",
  "167 CIE10",
  "168 RECOMENDACIÓN",
  "169 DIAGNOSTICO_12",
  "170 CIE10",
  "171 RECOMENDACIÓN",
  "172 APTITUD",
  "173 MOTIVO",
  "174 RESTRICCIONES"
)

names(my_data[[8]]) <- colnames8

my_data[[8]] <- my_data[[8]] |>
  mutate(`14 FECHA DE ATENCIÓN` = format(as.Date(`14 FECHA DE ATENCIÓN`, "%d-%m-%Y"), "%Y")) |>
  filter(!is.na(`1 NUMERO DE HISTORIA`)) |>
  # filter(!`N°` == "N°") |>
  rowid_to_column("ID") |>
  mutate(source = files[8])

my_data[[8]] <- my_data[[8]] |>
  select(anho = matches("FECHA DE ATENCIÓN"),
         id = matches("^ID$"),
         source = matches("source"),
         dni = matches("DNI"),
         edad = matches("EDAD"),
         sexo = matches("SEXO"),
         perabd = matches("45 PER"),
         presionarterial = matches("^PA$"),
         hb = matches("^HB$"),
         plaq = matches("^PLAQ"),
         leuc = matches("^LEUC"),
         glu = matches("^GLUCOSA"),
         ct = matches("COLESTEROL TOTAL"),
         trig = matches("TRIGLI"),
         hdl = matches("VALOR HDL"),
         ldl = matches("VALOR DE LDL"),
         presion_sis = matches("SIST"),
         presion_dia = matches("DIAST"),
         imc = matches("^[0-9]+ IMC"),
         fc = matches("F\\. CARD"),
         oftalmo = matches("^66 DIAG"),
         audio = matches("117 DIAG"),
         rx_torax = matches("135 DIAGN"),
         ekg = matches("^35 DIAGNOSTICO")) |>
  left_join(my_data[[11]] |> select(-edad), by)


### 9

my_data[[9]] <- my_data[[9]] |>
  mutate(`FECHA DE EMO` = format(as.Date(`FECHA DE EMO`, "%Y-%m-%d"), "%Y")) |>
  # filter(!is.na(`N°`)) |>
  # filter(!`N°` == "N°") |>
  rowid_to_column("ID") |>
  mutate(source = files[9])

my_data[[9]] <- my_data[[9]] |>
  select(anho = matches("FECHA DE EMO"),
         id = matches("^ID$"),
         source = matches("source"),
         dni = matches("DNI"),
         edad = matches("^EDAD"),
         sexo = matches("SEXO"),
         perabd = matches("PERIMETRO"),
         presionarterial = matches("^PA$"),
         hb = matches("^HB"),
         plaq = matches("^PLAQ"),
         leuc = matches("^LEUC"),
         glu = matches("^GLUCOSA"),
         ct = matches("COLESTERO$"),
         trig = matches("TRIGLI"),
         hdl = matches("^HDL"),
         ldl = matches("^LDL"),
         presion_sis = matches("PAS"),
         presion_dia = matches("PAD"),
         imc = matches("^IMC"),
         fc = matches("FC"),
         oftalmo = matches("OFTALMO"),
         audio = matches("AUDIO"),
         rx_torax = matches("torax$"),
         ekg = matches("EKG"))


### 10

my_data[[10]] <- my_data[[10]] |>
  mutate(`FECHA DE EMO` = format(as.Date(`FECHA DE EMO`, "%Y-%m-%d"), "%Y")) |>
  # filter(!is.na(`N°`)) |>
  # filter(!`N°` == "N°") |>
  rowid_to_column("ID") |>
  mutate(source = files[10])

my_data[[10]] <- my_data[[10]] |>
  select(anho = matches("FECHA DE EMO"),
         id = matches("^ID$"),
         source = matches("source"),
         dni = matches("DNI"),
         edad = matches("^EDAD"),
         sexo = matches("SEXO"),
         perabd = matches("PERIMETRO"),
         presionarterial = matches("^PA$"),
         hb = matches("^HB"),
         plaq = matches("^PLAQ"),
         leuc = matches("^LEUC"),
         glu = matches("^GLUCOSA"),
         ct = matches("COLESTERO$"),
         trig = matches("TRIGLI"),
         hdl = matches("^HDL"),
         ldl = matches("^LDL"),
         presion_sis = matches("PAS"),
         presion_dia = matches("PAD"),
         imc = matches("^IMC"),
         fc = matches("FC"),
         oftalmo = matches("OFTALMO"),
         audio = matches("AUDIO"),
         rx_torax = matches("torax$"),
         ekg = matches("EKG"))





## 12
my_data[[12]] <- my_data[[12]] |>
  mutate(`FECHA_EVALUACION` = format(as.Date(`FECHA_EVALUACION`, "%Y-%m-%d"), "%Y")) |>
  # filter(!is.na(`1 NUMERO DE HISTORIA`)) |>
  # filter(!`N°` == "N°") |>
  rowid_to_column("ID") |>
  mutate(source = files[12]) 

my_data[[12]] <- my_data[[12]] |>
  select(anho = matches("FECHA_EVALUACION"),
         id = matches("^ID$"),
         source = matches("source"),
         dni = matches("DNI"),
         edad = matches("^EDAD"),
         sexo = matches("SEXO"),
         perabd = matches("PERIMETRO"),
         presionarterial = matches("^PA$"),
         hb = matches("^HB"),
         plaq = matches("^PLAQ"),
         leuc = matches("^LEUC"),
         glu = matches("^GLUCOSA"),
         ct = matches("COLESTERO$"),
         trig = matches("TRIGLI"),
         hdl = matches("^HDL"),
         ldl = matches("^LDL"),
         presion_sis = matches("PAS"),
         presion_dia = matches("PAD"),
         imc = matches("^IMC"),
         fc = matches("FC"),
         oftalmo = matches("OFTALMO"),
         audio = matches("AUDIO"),
         rx_torax = matches("torax$"),
         ekg = matches("EKG"))



